const BASE_URL = '/api/v1';

export const API_ENDPOINTS = {
  AUTH: {
    LOGIN: `${BASE_URL}/auth/login`,
    REGISTER: `${BASE_URL}/auth/register`,
    LOGOUT: `${BASE_URL}/auth/logout`,
    REFRESH_TOKEN: `${BASE_URL}/auth/refresh`,
    FORGOT_PASSWORD: `${BASE_URL}/auth/forgot-password`,
    RESET_PASSWORD: `${BASE_URL}/auth/reset-password`,
    VERIFY_EMAIL: `${BASE_URL}/auth/verify-email`,
  },
  USERS: {
    ME: `${BASE_URL}/users/me`,
    UPDATE: `${BASE_URL}/users/me`,
    CHANGE_PASSWORD: `${BASE_URL}/users/change-password`,
    UPLOAD_AVATAR: `${BASE_URL}/users/avatar`,
    DELETE_ACCOUNT: `${BASE_URL}/users/me`,
    SEARCH: `${BASE_URL}/users/search`,
  },
  FRIENDS: {
    LIST: `${BASE_URL}/friends`,
    REQUESTS: `${BASE_URL}/friends/requests`,
    SEND_REQUEST: `${BASE_URL}/friends/request`,
    ACCEPT_REQUEST: (id) => `${BASE_URL}/friends/requests/${id}/accept`,
    REJECT_REQUEST: (id) => `${BASE_URL}/friends/requests/${id}/reject`,
    REMOVE: (id) => `${BASE_URL}/friends/${id}`,
    BALANCES: `${BASE_URL}/friends/balances`,
  },
  GROUPS: {
    LIST: `${BASE_URL}/groups`,
    CREATE: `${BASE_URL}/groups`,
    DETAIL: (id) => `${BASE_URL}/groups/${id}`,
    UPDATE: (id) => `${BASE_URL}/groups/${id}`,
    DELETE: (id) => `${BASE_URL}/groups/${id}`,
    MEMBERS: (id) => `${BASE_URL}/groups/${id}/members`,
    ADD_MEMBER: (id) => `${BASE_URL}/groups/${id}/members`,
    REMOVE_MEMBER: (groupId, userId) => `${BASE_URL}/groups/${groupId}/members/${userId}`,
    EXPENSES: (id) => `${BASE_URL}/groups/${id}/expenses`,
    SETTLE: (id) => `${BASE_URL}/groups/${id}/settle`,
  },
  EXPENSES: {
    LIST: `${BASE_URL}/expenses`,
    CREATE: `${BASE_URL}/expenses`,
    DETAIL: (id) => `${BASE_URL}/expenses/${id}`,
    UPDATE: (id) => `${BASE_URL}/expenses/${id}`,
    DELETE: (id) => `${BASE_URL}/expenses/${id}`,
    UPLOAD_RECEIPT: (id) => `${BASE_URL}/expenses/${id}/receipt`,
    SPLIT: (id) => `${BASE_URL}/expenses/${id}/split`,
    COMMENTS: (id) => `${BASE_URL}/expenses/${id}/comments`,
  },
  SETTLEMENTS: {
    LIST: `${BASE_URL}/settlements`,
    CREATE: `${BASE_URL}/settlements`,
    DETAIL: (id) => `${BASE_URL}/settlements/${id}`,
    UPDATE: (id) => `${BASE_URL}/settlements/${id}`,
    DELETE: (id) => `${BASE_URL}/settlements/${id}`,
  },
  TRANSACTIONS: {
    LIST: `${BASE_URL}/transactions`,
    CREATE: `${BASE_URL}/transactions`,
    DETAIL: (id) => `${BASE_URL}/transactions/${id}`,
    UPDATE: (id) => `${BASE_URL}/transactions/${id}`,
    DELETE: (id) => `${BASE_URL}/transactions/${id}`,
    CATEGORIES: `${BASE_URL}/transactions/categories`,
  },
  NOTIFICATIONS: {
    LIST: `${BASE_URL}/notifications`,
    MARK_READ: (id) => `${BASE_URL}/notifications/${id}/read`,
    MARK_ALL_READ: `${BASE_URL}/notifications/read-all`,
    DELETE: (id) => `${BASE_URL}/notifications/${id}`,
    SETTINGS: `${BASE_URL}/notifications/settings`,
  },
  ANALYTICS: {
    DASHBOARD: `${BASE_URL}/analytics/dashboard`,
    SPENDING_BY_CATEGORY: `${BASE_URL}/analytics/spending-by-category`,
    INCOME_VS_EXPENSE: `${BASE_URL}/analytics/income-vs-expense`,
    MONTHLY_TRENDS: `${BASE_URL}/analytics/monthly-trends`,
    FRIEND_BALANCES: `${BASE_URL}/analytics/friend-balances`,
  },
  CATEGORIES: {
    LIST: `${BASE_URL}/categories`,
    CREATE: `${BASE_URL}/categories`,
    UPDATE: (id) => `${BASE_URL}/categories/${id}`,
    DELETE: (id) => `${BASE_URL}/categories/${id}`,
  },
};